export const sampleBlogs = [
  {
    title: "The Rise of Quantum Computing",
    description: "Exploring how quantum computers are transforming problem-solving in technology and security.",
    category: "tech",
    author: "Lena Roberts",
    url: "https://images.unsplash.com/photo-1518770660439-4636190af475",
  },
  {
    title: "Sustainable Fashion in 2025",
    description: "How designers are making fashion more eco-friendly while staying stylish.",
    category: "fashion",
    author: "Elisa Grant",
     url: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f",  // e re
  },
  {
    title: "5 Hidden Nature Trails in Europe",
    description: "Discover breathtaking trails perfect for quiet hikes and scenic photography.",
    category: "nature",
    author: "Tomás Wilde",
    url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
  },
  {
    title: "Backpacking Across Southeast Asia",
    description: "My journey through Thailand, Vietnam, and Cambodia on a budget.",
    category: "travel",
    author: "Jasmine Tan",
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
  },
  {
    title: "Beginner's Guide to Home Workouts",
    description: "No equipment? No problem. Build strength and endurance at home.",
    category: "fitness",
    author: "Marcus Reed",
    url: "https://images.unsplash.com/photo-1605296867304-46d5465a13f1", // e re
  },
  {
    title: "Creating a Calming Morning Routine",
    description: "Simple steps to start your day with peace and purpose.",
    category: "lifestyle",
    author: "Camille Rivera",
    url: "https://images.unsplash.com/photo-1557683316-973673baf926",
  },
  {
    title: "Investing in Your 20s: Where to Start",
    description: "A millennial’s guide to growing wealth early.",
    category: "finance",
    author: "Jordan Kim",
    url: "https://images.unsplash.com/photo-1554224154-22dec7ec8818",
  },
  {
    title: "Latest Headlines You Shouldn't Miss",
    description: "A quick summary of today’s top global news stories.",
    category: "news",
    author: "Ava Schmidt",
    url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5", // e re
  },
  {
    title: "How to Start Your Own Business in 2025",
    description: "Tips for aspiring entrepreneurs to launch and grow.",
    category: "business",
    author: "Daniel Okafor",
    url: "https://images.unsplash.com/photo-1556740749-887f6717d7e4",
  },
  {
    title: "Top 10 TV Shows to Binge This Summer",
    description: "From drama to comedy, here’s what’s hot in 2025.",
    category: "entertainment",
    author: "Sophia Lee",
    url: "https://images.unsplash.com/photo-1525182008055-f88b95ff7980",
  },
  {
    title: "Handmade Clay Mugs: A Beginner's Tutorial",
    description: "Step-by-step on how to mold and paint your first pottery piece.",
    category: "crafts",
    author: "Greta Novak",
    url: "https://images.unsplash.com/photo-1512295767273-ac109ac3acfa",
  },
  {
    title: "Lo-fi Beats You Need in Your Playlist",
    description: "Relaxing background music for productivity and focus.",
    category: "music",
    author: "Noah Jackson",
    url: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4",
  },
  {
    title: "5-Minute Breakfast Recipes That Energize",
    description: "Nutritious meals you can prepare while half asleep.",
    category: "food",
    author: "Chiara Romano",
    url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836", // e re
  },
  {
    title: "Secrets Behind Viral Marketing Campaigns",
    description: "How brands are winning the internet with clever strategies.",
    category: "marketing",
    author: "Zayd El-Masri",
    url: "https://images.unsplash.com/photo-1523961131990-5ea7c61b2107",
  },
  {
    title: "How I Captured the Northern Lights",
    description: "A night under the stars with nothing but a camera and cold hands.",
    category: "photography",
    author: "Freya Lindholm",
    url: "https://images.unsplash.com/photo-1470770903676-69b98201ea1c",
  },
  {
    title: "Why We Need More Random Acts of Kindness",
    description: "The impact of small gestures in today’s digital age.",
    category: "others",
    author: "Zara Cohen",
    url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
  },
  {
    title: "AI in Everyday Life: Helpful or Harmful?",
    description: "Exploring the ethical dilemmas of AI adoption in 2025.",
    category: "all",
    author: "Amir Saeed",
    url: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b",
  },
];
